name: "PyPI"
mirrors:
  - tuna:
      link: "https://pypi.tuna.tsinghua.edu.cn"
references:
  description:
    url: "https://en.wikipedia.org/wiki/Python_Package_Index"
  steps:
    url: "https://mirrors.tuna.tsinghua.edu.cn/help/pypi/"
    license: "GNU GPLv2.0"
    license_url: "https://github.com/tuna/mirror-web/blob/master/LICENSE"
os:
  - name: "All"
