name: "Arch Linux"
mirrors:
  - ustc:
      link: "https://mirrors.ustc.edu.cn/archlinux"
  - tuna:
      link: "https://mirrors.tuna.tsinghua.edu.cn/archlinux"
references:
  description:
    url: "https://en.wikipedia.org/wiki/Arch_Linux"
  steps:
    url: "https://mirrors.ustc.edu.cn/help/archlinux.html"
    license: "CC BY-NC-SA 4.0"
    license_url: "https://creativecommons.org/licenses/by-nc-sa/4.0/"
os:
  - name: "Arch Linux"
