name: "Black Arch"
mirrors:
  - ustc:
      link: "https://mirrors.ustc.edu.cn/blackarch"
  - tuna:
      link: "https://mirrors.tuna.tsinghua.edu.cn/blackarch"
references:
  description:
    url: "https://en.wikipedia.org/wiki/BlackArch"
  steps:
    url: "https://mirrors.ustc.edu.cn/help/blackarch.html"
    license: "CC BY-NC-SA 4.0"
    license_url: "https://creativecommons.org/licenses/by-nc-sa/4.0/"
os:
  - name: "Black Arch"
