mirrors:
  - ustc:
      link: "https://mirrors.ustc.edu.cn/alpine"
  - tuna:
      link: "https://mirrors.tuna.tsinghua.edu.cn/alpine"
references:
  description:
    url: "https://en.wikipedia.org/wiki/Alpine_Linux"
  steps:
    url: "https://mirrors.ustc.edu.cn/help/alpine.html"
    license: "CC BY-NC-SA 4.0"
    license_url: "https://creativecommons.org/licenses/by-nc-sa/4.0/"
os:
  - name: "Alpine"
